REGISTRY: {}
args:
    com_port: /dev/ttyUSB0
    gripper_closed_position: '0.7929'
    gripper_force_multiplier: '0.5'
    gripper_max_force: '235.0'
    gripper_max_speed: '0.15'
    gripper_max_width: '0.085'
    gripper_speed_multiplier: '1.0'
    include_ros2_control: 'true'
    isaac_joint_commands: /isaac_joint_commands
    isaac_joint_states: /isaac_joint_states
    mock_sensor_commands: 'false'
    parent_link: ''
    sim_gazebo: 'false'
    sim_isaac: 'false'
    use_fake_hardware: 'false'
arm_mount: robotiq_85_base_link
base_link: base_link
base_mount: ''
base_rpy: 0.0 0.0 0.0
base_xyz: 0.0 0.0 0.0
config_dir: /home/bam/public_ws/src/ros2_robotiq_gripper/robotiq_description/urdf/config
config_file_name: robotiq_2f_85_2f_85_v0.0.0
config_file_path: /home/bam/public_ws/src/ros2_robotiq_gripper/robotiq_description/urdf/config/robotiq_2f_85_2f_85_v0.0.0.yaml
force_srdf_gen: 'false'
hash_config_file: 'false'
info:
    config_key: ''
    name: robotiq_2f_85
    sku: 2f_85
    type: Robotiq
    urdf_hash: ''
    uuid: ''
    version: 0.0.0
joints:
    robotiq_85_left_finger_tip_joint:
        can_id: '0'
        hardstop_position: '0.0'
        home_position: '0.0'
        initial_position: '0.0'
        is_fixed: 'false'
        limits:
            has_acceleration_limits: 'true'
            has_effort_limits: 'false'
            has_jerk_limits: 'true'
            has_position_limits: 'true'
            has_velocity_limits: 'true'
            max_acceleration: '10.0'
            max_effort: '0.0'
            max_jerk: '100.0'
            max_position: '3.141593'
            max_velocity: '10.0'
            min_acceleration: '-10.0'
            min_effort: '-0.0'
            min_jerk: '-100.0'
            min_position: '-3.141593'
            min_velocity: '-10.0'
        lock: 'false'
        lock_position: '0.0'
        mimic: 'true'
        name: robotiq_85_left_finger_tip_joint
        physics:
            damping: '0.0'
            friction: '0.0'
        transform:
            child_frame_id: ''
            frame_id: ''
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        unprefixed_name: robotiq_85_left_finger_tip_joint
    robotiq_85_left_inner_knuckle_joint:
        can_id: '0'
        hardstop_position: '0.0'
        home_position: '0.0'
        initial_position: '0.0'
        is_fixed: 'false'
        limits:
            has_acceleration_limits: 'true'
            has_effort_limits: 'false'
            has_jerk_limits: 'true'
            has_position_limits: 'true'
            has_velocity_limits: 'true'
            max_acceleration: '10.0'
            max_effort: '0.0'
            max_jerk: '100.0'
            max_position: '3.141593'
            max_velocity: '10.0'
            min_acceleration: '-10.0'
            min_effort: '-0.0'
            min_jerk: '-100.0'
            min_position: '-3.141593'
            min_velocity: '-10.0'
        lock: 'false'
        lock_position: '0.0'
        mimic: 'true'
        name: robotiq_85_left_inner_knuckle_joint
        physics:
            damping: '0.0'
            friction: '0.0'
        transform:
            child_frame_id: ''
            frame_id: ''
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        unprefixed_name: robotiq_85_left_inner_knuckle_joint
    robotiq_85_left_knuckle_joint:
        can_id: '0'
        hardstop_position: '0.0'
        home_position: '0.0'
        initial_position: '0.0'
        is_fixed: 'false'
        limits:
            has_acceleration_limits: 'true'
            has_effort_limits: 'false'
            has_jerk_limits: 'true'
            has_position_limits: 'true'
            has_velocity_limits: 'true'
            max_acceleration: '10.0'
            max_effort: '0.0'
            max_jerk: '100.0'
            max_position: '3.141593'
            max_velocity: '10.0'
            min_acceleration: '-10.0'
            min_effort: '-0.0'
            min_jerk: '-100.0'
            min_position: '-3.141593'
            min_velocity: '-10.0'
        lock: 'false'
        lock_position: '0.0'
        mimic: 'false'
        name: robotiq_85_left_knuckle_joint
        physics:
            damping: '0.0'
            friction: '0.0'
        transform:
            child_frame_id: ''
            frame_id: ''
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        unprefixed_name: robotiq_85_left_knuckle_joint
    robotiq_85_right_finger_tip_joint:
        can_id: '0'
        hardstop_position: '0.0'
        home_position: '0.0'
        initial_position: '0.0'
        is_fixed: 'false'
        limits:
            has_acceleration_limits: 'true'
            has_effort_limits: 'false'
            has_jerk_limits: 'true'
            has_position_limits: 'true'
            has_velocity_limits: 'true'
            max_acceleration: '10.0'
            max_effort: '0.0'
            max_jerk: '100.0'
            max_position: '3.141593'
            max_velocity: '10.0'
            min_acceleration: '-10.0'
            min_effort: '-0.0'
            min_jerk: '-100.0'
            min_position: '-3.141593'
            min_velocity: '-10.0'
        lock: 'false'
        lock_position: '0.0'
        mimic: 'true'
        name: robotiq_85_right_finger_tip_joint
        physics:
            damping: '0.0'
            friction: '0.0'
        transform:
            child_frame_id: ''
            frame_id: ''
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        unprefixed_name: robotiq_85_right_finger_tip_joint
    robotiq_85_right_inner_knuckle_joint:
        can_id: '0'
        hardstop_position: '0.0'
        home_position: '0.0'
        initial_position: '0.0'
        is_fixed: 'false'
        limits:
            has_acceleration_limits: 'true'
            has_effort_limits: 'false'
            has_jerk_limits: 'true'
            has_position_limits: 'true'
            has_velocity_limits: 'true'
            max_acceleration: '10.0'
            max_effort: '0.0'
            max_jerk: '100.0'
            max_position: '3.141593'
            max_velocity: '10.0'
            min_acceleration: '-10.0'
            min_effort: '-0.0'
            min_jerk: '-100.0'
            min_position: '-3.141593'
            min_velocity: '-10.0'
        lock: 'false'
        lock_position: '0.0'
        mimic: 'true'
        name: robotiq_85_right_inner_knuckle_joint
        physics:
            damping: '0.0'
            friction: '0.0'
        transform:
            child_frame_id: ''
            frame_id: ''
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        unprefixed_name: robotiq_85_right_inner_knuckle_joint
    robotiq_85_right_knuckle_joint:
        can_id: '0'
        hardstop_position: '0.0'
        home_position: '0.0'
        initial_position: '0.0'
        is_fixed: 'false'
        limits:
            has_acceleration_limits: 'true'
            has_effort_limits: 'false'
            has_jerk_limits: 'true'
            has_position_limits: 'true'
            has_velocity_limits: 'true'
            max_acceleration: '10.0'
            max_effort: '0.0'
            max_jerk: '100.0'
            max_position: '3.141593'
            max_velocity: '10.0'
            min_acceleration: '-10.0'
            min_effort: '-0.0'
            min_jerk: '-100.0'
            min_position: '-3.141593'
            min_velocity: '-10.0'
        lock: 'false'
        lock_position: '0.0'
        mimic: 'true'
        name: robotiq_85_right_knuckle_joint
        physics:
            damping: '0.0'
            friction: '0.0'
        transform:
            child_frame_id: ''
            frame_id: ''
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        unprefixed_name: robotiq_85_right_knuckle_joint
links:
    robotiq_85_base_link:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'true'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: robotiq_85_base_link
        scene_obj_collision: 'true'
        unprefixed_name: robotiq_85_base_link
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_left_finger_link:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: robotiq_85_left_finger_link
        scene_obj_collision: 'true'
        unprefixed_name: robotiq_85_left_finger_link
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_left_finger_tip_link:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: robotiq_85_left_finger_tip_link
        scene_obj_collision: 'true'
        unprefixed_name: robotiq_85_left_finger_tip_link
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_left_inner_knuckle_link:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: robotiq_85_left_inner_knuckle_link
        scene_obj_collision: 'true'
        unprefixed_name: robotiq_85_left_inner_knuckle_link
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_left_knuckle_link:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: robotiq_85_left_knuckle_link
        scene_obj_collision: 'true'
        unprefixed_name: robotiq_85_left_knuckle_link
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_right_finger_link:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: robotiq_85_right_finger_link
        scene_obj_collision: 'true'
        unprefixed_name: robotiq_85_right_finger_link
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_right_finger_tip_link:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: robotiq_85_right_finger_tip_link
        scene_obj_collision: 'true'
        unprefixed_name: robotiq_85_right_finger_tip_link
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_right_inner_knuckle_link:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: robotiq_85_right_inner_knuckle_link
        scene_obj_collision: 'true'
        unprefixed_name: robotiq_85_right_inner_knuckle_link
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_right_knuckle_link:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'false'
        name: robotiq_85_right_knuckle_link
        scene_obj_collision: 'true'
        unprefixed_name: robotiq_85_right_knuckle_link
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_tcp_tool:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'false'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'true'
        name: robotiq_85_tcp_tool
        scene_obj_collision: 'false'
        unprefixed_name: robotiq_85_tcp_tool
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
    robotiq_85_tcp_world:
        collision_geometry_size: 0.0 0.0 0.0
        collision_geometry_type: box
        collision_mesh_path: ''
        collision_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
        disable: 'false'
        display: 'true'
        inertial:
            inertia:
                ixx: '0.0'
                ixy: '0.0'
                ixz: '0.0'
                iyy: '0.0'
                iyz: '0.0'
                izz: '0.0'
            mass: '0.0'
            origin:
                x: '0.0'
                y: '0.0'
                z: '0.0'
        is_frame: 'true'
        name: robotiq_85_tcp_world
        scene_obj_collision: 'false'
        unprefixed_name: robotiq_85_tcp_world
        visual_mesh_path: ''
        visual_origin:
            rpy: 0.0 -0.0 0.0
            xyz: 0.0 0.0 0.0
lock_joints: 'false'
max_width: '0.085'
plugin: none
points_of_interest: []
positions:
    default_positions: initial
    joint_names: robotiq_85_left_knuckle_joint robotiq_85_right_knuckle_joint robotiq_85_left_inner_knuckle_joint
        robotiq_85_right_inner_knuckle_joint robotiq_85_left_finger_tip_joint robotiq_85_right_finger_tip_joint
    positions:
        initial: 0.0 0.0 0.0 0.0 0.0 0.0
prefix: ''
reflect: '1'
root_link: world
srdf:
    loaded_from_cache: 'false'
    macro_path: ''
    newly_generated: 'false'
    path: ''
    xacro_path: ''
tcp_tool: tcp_tool
tcp_world: tcp_world
tcp_world_floating: tcp_world_floating
urdf:
    macro_path: /home/bam/public_ws/src/ros2_robotiq_gripper/robotiq_description/urdf/robotiq_2f_85_macro.urdf.xacro
    mesh_package_name: /home/bam/public_ws/src/ros2_robotiq_gripper/robotiq_description
    path: ''
    xacro_path: /home/bam/public_ws/src/ros2_robotiq_gripper/robotiq_description/urdf/robotiq_2f_85_config.urdf.xacro
world_rpy: 0.0 0.0 0.0
world_xyz: 0.0 0.0 0.0
z_into_table: 'false'
